### ISSUE TITLE
Error in _get_kwarg function when handling lists as input

### ISSUE THREAD

**Issue by emmateki** [constantinpape/torch-em#227]
Hi,
firstly, I want to thanks for this repo! I've been using the 2D-UNet notebook, and I encountered an issue when attempting to add a description,tags,authors,... of the model as my input . I think that to enable both single and double quotes, the line of code should be modified to something like this ?
`val = val.replace(" ' ", ' " ')`

here is the line of code. 
https://github.com/constantinpape/torch-em/blob/b90721bb6665d339678f63f717c990c2c81b5c33/torch_em/util/modelzoo.py#L233

**Comment by constantinpape** [comment]
Sorry, I overlooked this issue at the time. But it is fixed now thanks to @anwai98. Thanks also for reporting the issue!
