### ISSUE TITLE
Request for DistributedDataParallel

### ISSUE THREAD

**Issue by sladenheim** [constantinpape/torch-em#229]
To allow for the training of larger models split across GPUS using the DefaultTrainer class, implement model parallel capabilities using the torch.DistributedDataParallel functionality.

**Comment by constantinpape** [comment]
Thanks for opening this @sladenheim. We are currently focusing on a new release of micro_sam, but will then look into this.

**Comment by constantinpape** [comment]
We support distributed training now via https://github.com/constantinpape/torch-em/blob/376247b8745768de205cd2bc9f681fa1b22ad28f/torch_em/multi_gpu_training.py .
We should document this, I will open up a follow up issue.
