### ISSUE TITLE
environment_cpu.yaml   does not exist (perhaps a typo or a missing channel

### ISSUE THREAD

**Issue by cdalinghaus** [constantinpape/torch-em#299]
The install instructions as per readme never worked for me:

`mamba create -f <ENV>.yaml -n <ENV_NAME>`

results in 
```
Looking for: ['environment_cpu.yaml']
(...)
The following package could not be installed
└─ environment_cpu.yaml   does not exist (perhaps a typo or a missing channel
```

The solution to this is to use the update command instead
`mamba env update -n <your-env> --file environment_cpu.yaml`

Source: https://github.com/mamba-org/mamba/issues/633

In case somebody else is facing the same issue.

**Comment by anwai98** [comment]
Hi @cdalinghaus,

Could you try using `mamba env create -f environment_cpu.yaml` to install the environment?

(this creates an environment with name `torch-em-cpu` by default - unless you specify using `-n <ENV_NAME>`)

**Comment by cdalinghaus** [comment]
Thanks @anwai98 .

I further tested it and it seems to work when I use
`mamba env create -f environment_cpu.yaml`

But when I use it without the **env**, as the readme suggests it does not work:

`mamba create -f environment_cpu.yaml -n test`

```
Looking for: ['environment_cpu.yaml']

warning  libmamba Cache file "/home/constantin/mambaforge/pkgs/cache/497deca9.json" was modified by another program
warning  libmamba Cache file "/home/constantin/mambaforge/pkgs/cache/09cdf8bf.json" was modified by another program
conda-forge/noarch                                  17.4MB @   3.5MB/s  5.5s
conda-forge/linux-64                                41.4MB @   4.6MB/s 10.2s
Could not solve for environment specs
The following package could not be installed
└─ environment_cpu.yaml   does not exist (perhaps a typo or a missing channel).
```

https://github.com/constantinpape/torch-em?tab=readme-ov-file#from-source

**Comment by constantinpape** [comment]
This is a typo in the readme, thanks for noticing @cdalinghaus . Both mamba and conda require the `env` in the command for creating environments from a file. I updated it.
