### ISSUE TITLE
Check HPA dataset processing

### ISSUE THREAD

**Issue by anwai98** [constantinpape/torch-em#350]
I think the design for processing images could change a bit.

Reason: The part for [`_process_image`](https://github.com/constantinpape/torch-em/blob/main/torch_em/data/datasets/light_microscopy/hpa.py#L261-L287) processes downloaded inputs in a selective-channel fashion (say compose the h5 files with 'nuclei' channel only - as the user requested for it). This might create an issue later to look for new channels. The only solution then is to remove the dataset and download it with the desired channel specification.

Solution: Store each channel into separate groups under `raw`: (say `raw/microtubules`, `raw/protein`, `raw/nuclei` and `raw/er`)

Do we think this is a good solution or should we opt for another way?

cc: @constantinpape

**Comment by constantinpape** [comment]
I think this is a good solution, but we then also need to combine the dataset to stack the selected channels on the fly.

**Comment by anwai98** [comment]
Updated at https://github.com/constantinpape/torch-em/pull/351.
