### ISSUE TITLE
Add support for multichannel compresed tif files

### ISSUE THREAD

**Issue by Czaki** [constantinpape/torch-em#92]
Currently `torch-em` support only reading files using `tifffile` only if could use `memmap` to read files

https://github.com/constantinpape/torch-em/blob/1487015f24cafdbc6e0079e99034e274d597cfcb/torch_em/util/image.py#L27-L32

but `memmap` could not be used if the file is saved with compression (from tifffile docs):
```
Memory-mapping requires the image data stored in native byte order,
    without tiling, compression, predictors, etc
```

the fallback is to use `imageio` that read-only 2d single channel data. Why not use `tifffile.imread` if the extension is `tif`, `tiff`, `TIF`, `TIFF`?  

Are you open to contributions?

**Comment by constantinpape** [comment]
> Why not use `tifffile.imread` if the extension is `tif`, `tiff`, `TIF`, `TIFF`?

Yes, that would make a lot of sense. A contribution would be very much appreciated.

**Comment by constantinpape** [comment]
Thanks for the contribution @Czaki. After merging I realized that you may need to check that the channel axis is loaded correctly to be passed to torch (it suspects channel first, I am not sure if tifffile will return channel last instead). Anyway, let me know if you run into any issues with training from multi-channel tifs; this might be a cause of them.

**Comment by Czaki** [comment]
The tiffile return axis is in the order as they are stored internally. 

If you want, I could add better reading code that will parse metadata to reorder axes

(I have such codes here https://github.com/4DNucleome/PartSeg/blob/50c69e497d788cfff4c81a8eccbcb0aeaa986891/package/PartSegImage/image_reader.py)

In the context of this, I have a question. 

I found that for the training model, there is a requirement channel to be the last axis (using `torch_em.default_segmentation_loader`), but it looks like `export_bioimageio_model` requires the channel to be first in the passed array. 
Did I'm correct?

**Comment by constantinpape** [comment]
> If you want, I could add better reading code that will parse metadata to reorder axes

Yes, that sounds good! (I have seen the new PR on this.)


> I found that for the training model, there is a requirement channel to be the last axis (using `torch_em.default_segmentation_loader`), but it looks like `export_bioimageio_model` requires the channel to be first in the passed array.
> Did I'm correct?

I don't think so. The channel axis should be first for `default_segmentation_loader`. (And note that you have to pass `channel_axis=True` if you have it).

**Comment by constantinpape** [comment]
> I don't think so. The channel axis should be first for `default_segmentation_loader`. (And note that you have to pass `channel_axis=True` if you have it).

Sorry, I was thinking about the `SegmentationDataset`, you might be right about the `ImageCollectionDataset` (and that should indeed be fixed). I will continue with the conversation in #94
